# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShoutAboutApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'Firebase/Storage'
pod 'Firebase/Auth'
pod 'Firebase/Database'
pod 'JSQMessagesViewController'
pod 'xmpp-messenger-ios'
pod 'CocoaLumberjack', '~> 2.4.0'

  # Pods for ShoutAboutApp

end


